### ISSUE TITLE
Build on Travis CI

### ISSUE THREAD

**Issue by shinnn** [gabrielgomesferraz/gulp-imagemin-demo#1]
Because Travis CI runs the test on the environment very similar to [yours](https://github.com/imagemin/imagemin/issues/133#issuecomment-149869614).

http://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

> Ubuntu 12.04 LTS Server Edition 64 bit

**Comment by gabrielgomesferraz** [comment]
Added the return gulp.src('app/assets/images/**') and continues with the same error, I also have an Mac OS here and also gives the same error.

**Comment by shinnn** [comment]
This comment https://github.com/gabrielgomesferraz/gulp-imagemin-demo/issues/1#issuecomment-150090851 is not related to this issue.

**Comment by gabrielgomesferraz** [comment]
From version 5.0.0 of node the error gulp-imagemin error with .gif no longer occurs

**Comment by shinnn** [comment]
Thanks :)
